package models;

public enum AppCategory {
    // --- FONTI DI CARBOIDRATI ---
    PASTA,
    RISO_E_CEREALI,
    PANE_E_SOSTITUTI,
    PATATE_E_TUBERI,
    FARINE,

    // --- COLAZIONE E DOLCI ---
    BISCOTTI_E_DOLCI_COLAZIONE,
    CEREALI_COLAZIONE,
    DOLCI_E_SNACK,
    CREME_SPALMABILI,

    // --- PROTEINE ---
    CARNE_BIANCA,
    CARNE_ROSSA,
    PESCE,
    AFFETTATI_E_SALUMI,
    UOVA,
    LEGUMI,

    // --- LATTICINI ---
    LATTE_E_BEVANDE_VEG,
    YOGURT_E_FERMENTATI,
    FORMAGGI,

    // --- ORTOFRUTTA ---
    FRUTTA_FRESCA,
    FRUTTA_SECCA,
    VERDURA,

    // --- CONDIMENTI ---
    OLIO_E_GRASSI,
    SALSE,

    BEVANDE,
    SCONOSCIUTO
}
